In [19]:
from __future__ import print_function
import tensorflow as tf
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers.convolutional import Conv2D
from keras.optimizers import Adam
from keras.layers.pooling import MaxPooling2D
from keras.callbacks import ModelCheckpoint,EarlyStopping
from keras.utils import to_categorical
from keras.models import load_model

import os
import dill as pickle
import numpy as np

In [20]:
from keras.datasets import cifar10

(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

In [21]:
print("Train Image Shape: ", train_images.shape)
print("Len of train labels:", len(train_labels))
train_labels

Train Image Shape:  (50000, 32, 32, 3)
Len of train labels: 50000


array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [22]:
print("Train Image Shape: ", test_images.shape)
print("Len of train labels:", len(test_labels))
test_labels

Train Image Shape:  (10000, 32, 32, 3)
Len of train labels: 10000


array([[3],
       [8],
       [8],
       ...,
       [5],
       [1],
       [7]])

In [23]:
def softmax(x):
    prob = []
    for i in x:
        b=i/np.sum(x)
        prob.append(b)
    return prob

In [24]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(32 * 32,)))
network.add(layers.Dense(10, activation='sigmoid'))

In [25]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [26]:
train_images = train_images.astype('float32')
test_images = test_images.astype('float32')
train_images /= 255
test_images /= 255
test_images.size

30720000

In [11]:
train_images = train_images.reshape((60000, 32 * 32,3))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 32 * 32,3))
test_images = test_images.astype('float32') / 255
train_images.size

ValueError: cannot reshape array of size 153600000 into shape (60000,1024,3)

In [30]:
from keras.utils import to_categorical
network.add(Conv2D(32, kernel_size=(3, 3), activation='relu',
                 input_shape=train_images.shape[60000,1024,3]))
network.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
network.add(MaxPooling2D(pool_size=(2, 2)))
network.add(Dropout(0.25))

network.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
network.add(MaxPooling2D(pool_size=(2, 2)))
network.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
network.add(MaxPooling2D(pool_size=(2, 2)))
network.add(Dropout(0.25))

network.add(Flatten())
network.add(Dense(1024, activation='relu'))
network.add(Dropout(0.5))
network.add(Dense(10, activation='sigmoid'))

TypeError: tuple indices must be integers or slices, not tuple

In [17]:
network.fit(train_images, train_labels, epochs=2, batch_size=128)

ValueError: Error when checking input: expected dense_1_input to have 2 dimensions, but got array with shape (50000, 32, 32, 3)

In [115]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 101us/step


In [116]:
print("Accuracy: ",test_acc,"\nTest Loss Value:",test_loss)

Accuracy:  0.98 
Test Loss Value: 0.06886653012689785


In [117]:
digit = train_images[0]
digit.shape
p=network.predict(test_images[0:1], verbose=1)
p

1/1 [==============================] - 0s 109ms/step


array([[2.1225972e-10, 7.4095102e-10, 6.0333932e-08, 3.3076380e-05,
        4.8285923e-14, 3.6433950e-10, 1.2545107e-15, 1.1463119e-01,
        1.7841652e-08, 7.2558592e-08]], dtype=float32)